### ISSUE TITLE
Compiling error when compiling windows 

### ISSUE THREAD

**Issue by johnkappa221** [godotengine/godot-mono-builds#3]
After executing windows.py configure --target=i686 --target=x86_64 --mxe-prefix=/usr

```
D:\godot-mono-builds-master\godot-mono-builds-master>windows.py make --target=i686 --target=x86_64 --mxe-prefix=/usr
Traceback (most recent call last):
  File "D:\godot-mono-builds-master\godot-mono-builds-master\windows.py", line 8, in <module>
    run_main(argv[1:], target_platform='windows')
  File "D:\godot-mono-builds-master\godot-mono-builds-master\desktop.py", line 208, in run_main
    cmd_utils.add_runtime_arguments(parser, default_help)
  File "D:\godot-mono-builds-master\godot-mono-builds-master\cmd_utils.py", line 59, in add_runtime_arguments
    add_base_arguments(parser, default_help)
  File "D:\godot-mono-builds-master\godot-mono-builds-master\cmd_utils.py", line 47, in add_base_arguments
    parser.add_argument('--configure-dir', default=path_join(home, 'mono-configs'), help=default_help)
  File "C:\New folder\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by neikeq** [comment]
This is explained in the README.

> Building on Windows is not supported. It's possible to use Cygwin or WSL (Windows Subsystem for Linux) but this hasn't been tested.

These scripts are for cross-compiling to Windows from Linux/macOS.

If you want to build Mono on Windows with Visual Studio, you can follow this guide: https://www.mono-project.com/docs/compiling-mono/windows/no-cygwin/
